### PR TITLE
Issue#4: Adding Test Cases

### PR DESCRIPTION
**Pull request by jonna01**
Adding String Validation Test Case to test UI Changes.

Adding Github Workflow/Actions to automation test changes.

### CODE REVIEW

**Comment by Gunturuwsu** [comment]
can you please provide evidence supporting your test cases and workflow.

**Comment by jonna01** [comment]
> can you please provide evidence supporting your test cases and workflow.

I have created a new repository in my local to specifically test my test cases and github workflows.
https://github.com/jonna01/Test_Cases/

Can you please check and validate my changes.

**Comment by Gunturuwsu** [comment]
I can see changes are working fine in your repository, proceeding with the merge.

**Comment by Gunturuwsu** [comment]
I dont see your changes are working in this repository as i tried doing some changes in one of my pull requests. 
Can you please check.

**Comment by jonna01** [comment]
I have re-opened new PR for this issue.

And changes are working fine with that change.
https://github.com/WSUCEG-7140/Team-Alpha/pull/27

**Pull request merged**
